language: csharp
dist: xenial
sudo: required
mono: none
dotnet: 3.1
services:
  - docker

branches:
  only:
    - master
    - develop

before_script:
  - chmod -R a+x scripts
  - docker build -t matiasgramkow23/unit-test-docker -f ./unit-testing-using-dotnet-test/Dockerfile ./unit-testing-using-dotnet-test

script:
  - ./scripts/dotnet-test.sh

after_success:
  - ./scripts/after-success.sh
  - ./scripts/docker-login.sh
  - ./scripts/docker-push.sh

notifications:
  email:
    on_success: never
    on_failure: always